CREATE OR REPLACE VIEW SICRESAP.SICREVI_ENTR_02 AS
SELECT 
    A.TKNUM AS DT,
    B.TPNUM AS POSICION,
    C.VBELN_ORD_ENT AS ID_ENTREGA,
    C.vgbel AS ID_PEDIDO,
    C.XBLNR_GR AS GUIA,
    CL.CLIEV_IDCLIENTE_SAP AS ID_DESTINATARIO,
    CL.DICLV_DIRECCION AS DIRECCION,
    CL.CLIEV_IDCLIENTE AS ID_CLIENTE,
    A.ERDAT AS FECHA_DOCUMENTO,
    TO_DATE(TO_CHAR (C.LIKP_FDAT, 'dd/mm/yyyy') || ' ' || C.LIKP_LFUHR, 'dd/mm/yyyy HH24:MI:SS') AS FECHA_HORA_ENTREGA,
    C.BTGEW AS PESO,
    A.SIGNI AS PLACA,
    CASE
        WHEN C.STCD1 IS NOT NULL
        THEN
        C.STCD1
        ELSE
        (SELECT STCD1
            FROM SAPIO.SD_SLS_033E_DATOSGRALPROVEEDOR
            WHERE lifnr = A.TDLNR)
    END
        AS RUC_EMPRESA,
    C.GEWEI AS UNIDAD_PESO,
    CL.DICLN_LATITUD AS LATITUD,
    CL.DICLN_LONGITUD AS LONGITUD,
    PED.PECAV_RUTA_CODIGO_OFICINA AS CODIGO_OFICINA,
    PED.PECAV_RUTA_COD_GRUPO_VENDEDOR AS GRUPO_VENDEDOR,
    PED.PECAV_SOCIEDAD AS SOCIEDAD,
    PED.PECAV_CANAL_DIST AS CANAL_DIST,
    PED.PECAV_DIRECCION_REPARTO AS DIRECCION_REPARTO
FROM SAPIO.SD_TRA_001_DOC_TRANSP_CAB A
JOIN SAPIO.SD_TRA_001_DOC_TRANSP_DET B ON A.TKNUM = B.TKNUM
JOIN SAPIO.SD_SLS_ERP_115_GUIA_REM_CAB C ON B.VBELN = C.VBELN_ORD_ENT
JOIN SAPIO.SCOGVST_PEDIDO_CABECERA PED ON PED.PECAV_ID_NUMERO_PEDIDO = C.VGBEL
JOIN SAPIO.SECLIST_DIRECCION_CLIENTE CL
    ON (PED.PECAV_DIRECCION_REPARTO = CL.CLIEV_IDCLIENTE
        AND PED.PECAV_DIRECCION_REPARTO = CL.CLIEV_IDCLIENTE_SAP
        AND PED.PECAV_SOCIEDAD = CL.SOCIV_IDSOCIEDAD
        AND PED.PECAV_ORG_VENTAS = CL.ORVEV_IDORGANIZACION_VENTAS
        AND PED.PECAV_CANAL_DIST = CL.CADIV_IDCANAL_DISTRIBUCION
        AND CL.DICLV_IDTIPO_DIRECCION = 'RP')
WHERE A.ERDAT > ADD_MONTHS(SYSDATE, -6)
    AND C.VBELN_ORD_ENT IS NOT NULL
    AND C.vgbel IS NOT NULL
    AND C.LIKP_BLDAT IS NOT NULL
    AND C.LIKP_FDAT IS NOT NULL
    AND C.LIKP_LFUHR IS NOT NULL
    AND A.SIGNI IS NOT NULL;