-------------------
-- TABLA DOMINIO --
-------------------
CREATE TABLE "SICRESAP"."CONFIGT_DOMINIO" 
   (	"ID_DOMINIO" NUMBER(9,0) NOT NULL ENABLE, 
	"APPCODE" VARCHAR2(12 CHAR) NOT NULL ENABLE, 
	"CODIGO_DOMINIO" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200 CHAR), 
	"CREADO_POR" VARCHAR2(20 CHAR), 
	"FECHA_CREACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(20 CHAR), 
	"FECHA_MODIFICACION" DATE, 
	"COD_ESTADO" VARCHAR2(2 CHAR) DEFAULT '1' NOT NULL ENABLE, 
	"FLAG_CONFIG_SISTEMA" VARCHAR2(2 CHAR) DEFAULT '0' NOT NULL ENABLE, 
	 CONSTRAINT "SICRESAPNPK_CFDM_01" PRIMARY KEY ("ID_DOMINIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXTS"  ENABLE, 
	 CONSTRAINT "SICRESAPNUN_CFDM_02" UNIQUE ("APPCODE", "CODIGO_DOMINIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATS"   NO INMEMORY ;

   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."ID_DOMINIO" IS 'Id de dominio';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."APPCODE" IS 'Nombre de aplicación';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."CODIGO_DOMINIO" IS 'código de dominio';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."DESCRIPCION" IS 'Descripción de dolinio';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."CREADO_POR" IS 'Usuario de creación';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."FECHA_CREACION" IS 'Fecha de creación';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."MODIFICADO_POR" IS 'Usuario de modificación';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."FECHA_MODIFICACION" IS 'Fecha de modificación';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."COD_ESTADO" IS 'Codigo de estado 0 inactivo, 1 activo, 2 borrado';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_DOMINIO"."FLAG_CONFIG_SISTEMA" IS 'Flag parametro de sistema 1';

---------------------
-- TABLA PARAMETRO --
---------------------
CREATE TABLE "SICRESAP"."CONFIGT_PARAMETRO" 
   (	"ID_PARAMETRO" NUMBER(9,0) NOT NULL ENABLE, 
	"COD_ESTADO" VARCHAR2(2 CHAR) DEFAULT '1' NOT NULL ENABLE, 
	"APPCODE" VARCHAR2(12 CHAR) NOT NULL ENABLE, 
	"CODIGO_DOMINIO" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(800 CHAR), 
	"VALOR_PARAMETRO" VARCHAR2(800 CHAR), 
	"VALOR_PARAMETRO2" VARCHAR2(2000 CHAR), 
	"VALOR_PARAMETRO3" VARCHAR2(3000 CHAR), 
	"VALOR_PARAMETRO4" VARCHAR2(3000 CHAR), 
	"CREADO_POR" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	"MODIFICADO_POR" VARCHAR2(20 CHAR), 
	"FECHA_MODIFICACION" DATE, 
	"CODIGO_DOMINIO_PADRE" VARCHAR2(20 CHAR), 
	"VALOR_PARAMETRO_PADRE" VARCHAR2(800 CHAR), 
	 CONSTRAINT "SICRESAPNPK_CFPM_01" PRIMARY KEY ("ID_PARAMETRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATS"   NO INMEMORY ;

   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."ID_PARAMETRO" IS 'Id secuencial de parametro';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."COD_ESTADO" IS 'Codigo de estado estandar 0 inactivo, 1 Activo, 2 Borrado';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."APPCODE" IS 'Nombre Aplicación';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."CODIGO_DOMINIO" IS 'Codigo de dominio';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."DESCRIPCION" IS 'Descripción';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."VALOR_PARAMETRO" IS 'Valor principal';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."VALOR_PARAMETRO2" IS 'Valor secundario 1';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."VALOR_PARAMETRO3" IS 'Valor secundario 2';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."VALOR_PARAMETRO4" IS 'Valor secundario 3';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."CREADO_POR" IS 'Usuario creación registro';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."FECHA_CREACION" IS 'Fecha creación';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."MODIFICADO_POR" IS 'Usuario modificación registro';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."FECHA_MODIFICACION" IS 'Fecha modificación';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."CODIGO_DOMINIO_PADRE" IS 'Codigo de dominio padre';
   COMMENT ON COLUMN "SICRESAP"."CONFIGT_PARAMETRO"."VALOR_PARAMETRO_PADRE" IS 'Valor de parametro padre';

