---------------------------
-- 01. OPERATIVO PERMISO --
---------------------------
CREATE TABLE SICRESAP.SICRESAPT_OPERATIVO_PERMISO (
    "OPERN_ID" NUMBER(9, 0) NOT NULL,
    "OPERV_PLACA" VARCHAR2(32),
    "OPERV_POLITICA_PRIVACIDAD" VARCHAR2(2),
    "OPERV_PERMISO_UBICACION" VARCHAR2(2),
    "OPERV_USUARIO_CREACION" VARCHAR2(32),
    "OPERD_FECHA_CREACION" DATE,
    "OPERV_USUARIO_MODIFICACION" VARCHAR2(32),
    "OPERD_FECHA_MODIFICACION" DATE,
    "OPERN_ESTADO" NUMBER(1) DEFAULT 1)
    LOGGING 
    TABLESPACE DATATS 
    PCTFREE 10 
    INITRANS 1 
    STORAGE 
    ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
    ) 
    NOCOMPRESS 
    NO INMEMORY 
    NOPARALLEL; 
    
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERN_ID IS 'ID Operativo Permiso';
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERV_PLACA IS 'Placa del Transportista';
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERV_POLITICA_PRIVACIDAD IS 'Acepta Política Privacidad';
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERV_PERMISO_UBICACION IS 'Acepta Permiso Ubicación';
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERV_USUARIO_CREACION IS 'Usuario de Creacion';
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERD_FECHA_CREACION IS 'Fecha de Creacion';
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERV_USUARIO_MODIFICACION IS 'Usuario de Modificacion';
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERD_FECHA_MODIFICACION IS 'Fecha de Modificacion';
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERN_ESTADO IS 'Estado';

CREATE UNIQUE INDEX SICRESAP.SICRESID_OPER_01 ON SICRESAP.SICRESAPT_OPERATIVO_PERMISO (OPERN_ID ASC)
LOGGING 
TABLESPACE INDEXTS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE SICRESAP.SICRESAPT_OPERATIVO_PERMISO ADD (
  CONSTRAINT SICRESPK_OPER_01 PRIMARY KEY (OPERN_ID)
  USING INDEX SICRESAP.SICRESID_OPER_01 ENABLE VALIDATE);