ALTER TABLE SICRESAP.SICRESAPT_OPERATIVO_PERMISO ADD OPERN_CANTIDAD_MOSTRAR NUMBER(1,0) DEFAULT 1;
COMMENT ON COLUMN SICRESAP.SICRESAPT_OPERATIVO_PERMISO.OPERN_CANTIDAD_MOSTRAR IS 'Numero de veces a mostrar politicas y permiso de ubicacion';

--REGISTRAR PERMISOS PLACA
SET DEFINE OFF;
INSERT INTO SICRESAP.SICRESAPT_OPERATIVO_FECHAS (OFECN_ID_OPER_FECHA,OFECV_NRO_LISTA,OFECV_TIPO_OPERACION,OFECD_FECHA_INI_OPERATIVO,OFECD_FECHA_FIN_OPERATIVO,-,OFECD_FECHA_CREACION,OFECV_USUARIO_MODIFICACION,OFECD_FECHA_MODIFICACION,OFECD_ESTADO) VALUES (1,1,'I',to_date('22/12/23','DD/MM/RR'),to_date('31/01/24','DD/MM/RR'),'ybazalar',SYSDATE,null,null,1);

INSERT INTO SICRESAP.SICRESAPT_OPERATIVO_PLACAS (OPLAN_ID_OPERATIVO,OPLAN_ID_CABECERA,OPLAN_TIPO_OPERACION,OPLAV_NRO_LISTA,OPLAV_PLACA,OPLAV_ID_PROVEEDOR,OPLAV_PROVEEDOR,OPLAV_HORARIO,OPLAD_FECHA_INI_OPERATIVO,OPLAD_FECHA_FIN_OPERATIVO,OPLAV_USUARIO_CREACION,OPLAD_FECHA_CREACION,OPLAV_USUARIO_MODIFICACION,OPLAD_FECHA_MODIFICACION,OPLAN_ESTADO) VALUES (3,1,'I',1,'A0U912',2056589488,'VIAJES S.A.','M',to_date('22/12/23','DD/MM/RR'),to_date('31/01/24','DD/MM/RR'),'ybazalar',SYSDATE,'ybazalar',SYSDATE,1);

INSERT INTO SICRESAP.SICRESAPT_OPERATIVO_PERMISO (OPERN_ID,OPERV_PLACA,OPERV_POLITICA_PRIVACIDAD,OPERV_PERMISO_UBICACION,OPERV_USUARIO_CREACION,OPERD_FECHA_CREACION,OPERV_USUARIO_MODIFICACION,OPERD_FECHA_MODIFICACION,OPERN_ESTADO,OPERN_CANTIDAD_MOSTRAR) VALUES ('5','A0U912','N','N','A0U912',SYSDATE,'A0U912',SYSDATE,'1','0');
COMMIT;

