GRANT SELECT ON SICRESAP.SICRESAPT_OPERATIVO_FECHAS TO CONSULTA;
GRANT SELECT ON SICRESAP.SICRESAPT_OPERATIVO_PERMISO TO CONSULTA;
GRANT SELECT ON SICRESAP.SICRESAPT_OPERATIVO_PLACAS TO CONSULTA;

GRANT SELECT ON SICRESAP.SITPEST_PARAMETRO TO CONSULTA;

GRANT SELECT ON SICRESAP.CONFIGT_DOMINIO TO CONSULTA;
GRANT SELECT ON SICRESAP.CONFIGT_PARAMETRO TO CONSULTA;
GRANT SELECT ON SICRESAP.ACDIMT_CHECKLIST_ARCHIVO TO CONSULTA;
GRANT SELECT ON SICRESAP.ACDIMT_COMENTARIO TO CONSULTA;
GRANT SELECT ON SICRESAP.ACDIMT_DT_ESTADO TO CONSULTA;
GRANT SELECT ON SICRESAP.ACDIMT_ITEM_CHECKLIST TO CONSULTA;
GRANT SELECT ON SICRESAP.ACDIMT_ITEM_CHECKLIST_HIST TO CONSULTA;
GRANT SELECT ON SICRESAP.ACDIMT_PREGUNTA TO CONSULTA;