GRANT SELECT ON SICRESAP.SICRESAPT_OPERATIVO_FECHAS TO CONSULTA;
GRANT SELECT ON SICRESAP.SICRESAPT_OPERATIVO_PERMISO TO CONSULTA;
GRANT SELECT ON SICRESAP.SICRESAPT_OPERATIVO_PLACAS TO CONSULTA;

GRANT SELECT ON SICRESAP.SITPEST_PARAMETRO TO CONSULTA;