REM INSERTING into SICRESAP.SICRESAPT_RUTA_UBICACIONES
SET DEFINE OFF;
INSERT INTO SICRESAP.SICRESAPT_RUTA_UBICACIONES (RUUBN_ID_RUTA_UBICACION,RUUBV_TIPO_OPERACION,RUUBV_ORIGEN_LATITUD,RUUBV_ORIGEN_LONGITUD,RUUBV_DESTINO_LATITUD,RUUBV_DESTINO_LONGITUD,RUUBN_ESTADO,RUUBD_FECHA_CREACION,RUUBV_USUARIO_CREACION,RUUBD_FECHA_MODIFICACION,RUUBV_USUARIO_MODIFICACION) VALUES ('1','I','-13.80466','-76.29408','-13.79049','-76.16714','1',to_date('25/08/23','DD/MM/RR'),'admin',null,null);
INSERT INTO SICRESAP.SICRESAPT_RUTA_UBICACIONES (RUUBN_ID_RUTA_UBICACION,RUUBV_TIPO_OPERACION,RUUBV_ORIGEN_LATITUD,RUUBV_ORIGEN_LONGITUD,RUUBV_DESTINO_LATITUD,RUUBV_DESTINO_LONGITUD,RUUBN_ESTADO,RUUBD_FECHA_CREACION,RUUBV_USUARIO_CREACION,RUUBD_FECHA_MODIFICACION,RUUBV_USUARIO_MODIFICACION) VALUES ('2','E','-13.79049','-76.16714','-13.80466','-76.29408','1',to_date('25/08/23','DD/MM/RR'),'admin',null,null);
COMMIT;
