---------------------------
-- 01. CHECKLIST ARCHIVO --
---------------------------
CREATE TABLE SICRESAP.ACDIMT_CHECKLIST_ARCHIVO (
    "ID" NUMBER(9, 0) NOT NULL,
    "DT" VARCHAR2(20) NOT NULL,
    "NOMBRE" VARCHAR2(128) NOT NULL,
    "USUARIO_CREACION" VARCHAR2(32),
    "FECHA_CREACION" DATE,
    "USUARIO_MODIFICACION" VARCHAR2(32),
    "FECHA_MODIFICACION" DATE,
    "ESTADO" NUMBER(1) DEFAULT 1)
    LOGGING 
    TABLESPACE DATATS 
    PCTFREE 10 
    INITRANS 1 
    STORAGE 
    ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
    ) 
    NOCOMPRESS 
    NO INMEMORY 
    NOPARALLEL; 
    
COMMENT ON COLUMN SICRESAP.ACDIMT_CHECKLIST_ARCHIVO.ID IS 'ID Checklist Archivo';
COMMENT ON COLUMN SICRESAP.ACDIMT_CHECKLIST_ARCHIVO.DT IS 'Documento de Transporte';
COMMENT ON COLUMN SICRESAP.ACDIMT_CHECKLIST_ARCHIVO.NOMBRE IS 'Nombre del Archivo';
COMMENT ON COLUMN SICRESAP.ACDIMT_CHECKLIST_ARCHIVO.USUARIO_CREACION IS 'Usuario de Creacion';
COMMENT ON COLUMN SICRESAP.ACDIMT_CHECKLIST_ARCHIVO.FECHA_CREACION IS 'Fecha de Creacion';
COMMENT ON COLUMN SICRESAP.ACDIMT_CHECKLIST_ARCHIVO.USUARIO_MODIFICACION IS 'Usuario de Modificacion';
COMMENT ON COLUMN SICRESAP.ACDIMT_CHECKLIST_ARCHIVO.FECHA_MODIFICACION IS 'Fecha de Modificacion';
COMMENT ON COLUMN SICRESAP.ACDIMT_CHECKLIST_ARCHIVO.ESTADO IS 'Estado';

CREATE UNIQUE INDEX SICRESAP.ACDIMID_CHAR_01 ON SICRESAP.ACDIMT_CHECKLIST_ARCHIVO (ID ASC)
LOGGING 
TABLESPACE INDEXTS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE SICRESAP.ACDIMT_CHECKLIST_ARCHIVO ADD (
  CONSTRAINT ACDIMPK_CHAR_01 PRIMARY KEY (ID)
  USING INDEX SICRESAP.ACDIMID_CHAR_01 ENABLE VALIDATE);

---------------------------
-- 01. COMENTARIO --
---------------------------
CREATE TABLE "SICRESAP"."ACDIMT_COMENTARIO" (
  "ID_COMENTARIO" NUMBER(12,0) NOT NULL ENABLE, 
	"TIPO_USUARIO" VARCHAR2(5 BYTE), 
	"COMENTARIO" VARCHAR2(200 BYTE), 
	"SEGUV_ESTADO" VARCHAR2(2 BYTE), 
	"SEGUV_USR_CREACION" VARCHAR2(20 BYTE), 
	"SEGUD_FECHA_CREACION" DATE, 
	"SEGUV_USR_MODIFICACION" VARCHAR2(20 BYTE), 
	"SEGUD_FECHA_MODIFICACION" DATE, 
	"ID_CHECKLIST" NUMBER(12,0) NOT NULL ENABLE, 
	CONSTRAINT "ACDIMPK_COMENTARIO_01" PRIMARY KEY ("ID_COMENTARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXTS"  ENABLE
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATATS"   NO INMEMORY ;

---------------------------
-- 01. DT ESTADO --
---------------------------
CREATE TABLE "SICRESAP"."ACDIMT_DT_ESTADO" (
  "DT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TIPO_USUARIO" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2 BYTE) DEFAULT 1, 
	"USR_CREACION" VARCHAR2(20 BYTE), 
	"USR_MODIFICACION" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	"PLACA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COMENTARIO_SUPERVISOR" VARCHAR2(1000 BYTE), 
	"USR_SUPERVISOR" VARCHAR2(20 BYTE), 
	CONSTRAINT "ACDIMPK_DT_ESTADO_01" PRIMARY KEY ("DT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATATS"  ENABLE
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATATS"   NO INMEMORY ;

---------------------------
-- 01. ITEM CHECKLIST --
---------------------------
CREATE TABLE "SICRESAP"."ACDIMT_ITEM_CHECKLIST" (
  "ID_CHECKLIST" NUMBER(12,0) NOT NULL ENABLE, 
	"DT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID_PREGUNTA" NUMBER(9,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2 BYTE) DEFAULT -1, 
	"USR_CREACION" VARCHAR2(20 BYTE), 
	"USR_MODIFICACION" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
  CONSTRAINT "ACDIMPK_ITEM_CHECKLIST_01" PRIMARY KEY ("ID_CHECKLIST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXTS"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATATS"   NO INMEMORY ;

---------------------------
-- 01. ITEM CHECKLIST HIST--
---------------------------
CREATE TABLE "SICRESAP"."ACDIMT_ITEM_CHECKLIST_HIST" (
  "ID_CHECKLIST" NUMBER(12,0) NOT NULL ENABLE, 
	"DT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID_PREGUNTA" NUMBER(9,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2 BYTE) DEFAULT 1, 
	"USR_CREACION" VARCHAR2(20 BYTE), 
	"USR_MODIFICACION" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	CONSTRAINT "ACDIMPK_ITEM_CHECKLIST_HIST_01" PRIMARY KEY ("ID_CHECKLIST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXTS"  ENABLE
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATATS"   NO INMEMORY ;

---------------------------
-- 01. ITEM PREGUNTA --
---------------------------
CREATE TABLE "SICRESAP"."ACDIMT_PREGUNTA" (
  "ID_PREGUNTA" NUMBER(12,0) NOT NULL ENABLE, 
	"CODIGO_PREGUNTA" VARCHAR2(2 BYTE), 
	"GRUPO_PREGUNTA" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"ESTADO" VARCHAR2(2 BYTE), 
	"USR_CREACION" VARCHAR2(20 BYTE), 
	"USR_MODIFICACION" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_MODIFICACION" DATE, 
	CONSTRAINT "ACDIMPK_PREGUNTA_01" PRIMARY KEY ("ID_PREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXTS"  ENABLE
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATATS"   NO INMEMORY ;

--SECUENCIAS
CREATE SEQUENCE SICRESAP.ACDIMSQ_CHECKLIST_ARCHIVO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SICRESAP.ACDIMSQ_COMENTARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SICRESAP.ACDIMSQ_ITEM_CHECKLIST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SICRESAP.ACDIMSQ_ITEM_CHECKLIST_HIST START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SICRESAP.ACDIMSQ_PREGUNTA START WITH 10 INCREMENT BY 1;

--GRANTS
GRANT SELECT ON "SICRESAP"."ACDIMT_CHECKLIST_ARCHIVO" TO "ACDIMC4C";
GRANT SELECT ON "SICRESAP"."ACDIMT_PREGUNTA" TO "ACDIMC4C";
GRANT SELECT ON "SICRESAP"."ACDIMT_ITEM_CHECKLIST" TO "ACDIMC4C";
GRANT SELECT ON "SICRESAP"."ACDIMT_COMENTARIO" TO "ACDIMC4C";
GRANT SELECT ON "SICRESAP"."ACDIMT_DT_ESTADO" TO "ACDIMC4C";