SET DEFINE OFF;

--DOMINIO
INSERT INTO SICRESAP.CONFIGT_DOMINIO (ID_DOMINIO,APPCODE,CODIGO_DOMINIO,DESCRIPCION,CREADO_POR,FECHA_CREACION,MODIFICADO_POR,FECHA_MODIFICACION,COD_ESTADO,FLAG_CONFIG_SISTEMA) VALUES ('5','ACEROSTRACK','D005','Tipo de Pedido para Despacho','admin',SYSDATE,null,null,'1','0');
INSERT INTO SICRESAP.CONFIGT_DOMINIO (ID_DOMINIO,APPCODE,CODIGO_DOMINIO,DESCRIPCION,CREADO_POR,FECHA_CREACION,MODIFICADO_POR,FECHA_MODIFICACION,COD_ESTADO,FLAG_CONFIG_SISTEMA) VALUES ('6','ACEROSTRACK','D006','Tipo de Pedido para ACEDIM Checklist','admin',SYSDATE,null,null,'1','0');

--PARAMETRO
INSERT INTO SICRESAP.CONFIGT_PARAMETRO (ID_PARAMETRO,COD_ESTADO,APPCODE,CODIGO_DOMINIO,DESCRIPCION,VALOR_PARAMETRO,VALOR_PARAMETRO2,VALOR_PARAMETRO3,VALOR_PARAMETRO4,CREADO_POR,FECHA_CREACION,MODIFICADO_POR,FECHA_MODIFICACION,CODIGO_DOMINIO_PADRE,VALOR_PARAMETRO_PADRE) VALUES ('37','1','ACEROSTRACK','D005','ZMST','ZMST',null,null,null,'admin',SYSDATE,null,null,null,null);
INSERT INTO SICRESAP.CONFIGT_PARAMETRO (ID_PARAMETRO,COD_ESTADO,APPCODE,CODIGO_DOMINIO,DESCRIPCION,VALOR_PARAMETRO,VALOR_PARAMETRO2,VALOR_PARAMETRO3,VALOR_PARAMETRO4,CREADO_POR,FECHA_CREACION,MODIFICADO_POR,FECHA_MODIFICACION,CODIGO_DOMINIO_PADRE,VALOR_PARAMETRO_PADRE) VALUES ('38','1','ACEROSTRACK','D005','ZPVT','ZPVT',null,null,null,'admin',SYSDATE,null,null,null,null);
INSERT INTO SICRESAP.CONFIGT_PARAMETRO (ID_PARAMETRO,COD_ESTADO,APPCODE,CODIGO_DOMINIO,DESCRIPCION,VALOR_PARAMETRO,VALOR_PARAMETRO2,VALOR_PARAMETRO3,VALOR_PARAMETRO4,CREADO_POR,FECHA_CREACION,MODIFICADO_POR,FECHA_MODIFICACION,CODIGO_DOMINIO_PADRE,VALOR_PARAMETRO_PADRE) VALUES ('39','1','ACEROSTRACK','D006','ZDIM','ZDIM',null,null,null,'admin',SYSDATE,null,null,null,null);
INSERT INTO SICRESAP.CONFIGT_PARAMETRO (ID_PARAMETRO,COD_ESTADO,APPCODE,CODIGO_DOMINIO,DESCRIPCION,VALOR_PARAMETRO,VALOR_PARAMETRO2,VALOR_PARAMETRO3,VALOR_PARAMETRO4,CREADO_POR,FECHA_CREACION,MODIFICADO_POR,FECHA_MODIFICACION,CODIGO_DOMINIO_PADRE,VALOR_PARAMETRO_PADRE) VALUES ('40','1','ACEROSTRACK','D006','ZMST','ZMST',null,null,null,'admin',SYSDATE,null,null,null,null);
INSERT INTO SICRESAP.CONFIGT_PARAMETRO (ID_PARAMETRO,COD_ESTADO,APPCODE,CODIGO_DOMINIO,DESCRIPCION,VALOR_PARAMETRO,VALOR_PARAMETRO2,VALOR_PARAMETRO3,VALOR_PARAMETRO4,CREADO_POR,FECHA_CREACION,MODIFICADO_POR,FECHA_MODIFICACION,CODIGO_DOMINIO_PADRE,VALOR_PARAMETRO_PADRE) VALUES ('41','1','ACEROSTRACK','D005','ZDIM','ZDIM',null,null,null,'admin',SYSDATE,null,null,null,null);

COMMIT;